set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'rust-lang/rust.vim'
Plugin 'flazz/vim-colorschemes'
Plugin 'editorconfig/editorconfig-vim'

call vundle#end()

filetype plugin indent on
set clipboard=unnamedplus
set expandtab
set shiftwidth=4
set softtabstop=4
set number
colorscheme Tomorrow-Night
